markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

name: 'worldgreatkim Blog'
description: 'My tech blog powered by Jekyll and GitHub Pages'
google_analytics: ''
disqus: ''

baseurl: ''
url: "https://worldgreatkim.github.io"

permalink: /:title

plugins: [jekyll-paginate]

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
  - .git
